name: mypy

on:
  push:
    branches:
      - v3


jobs:
  mypy:
    name: Type Check with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install mypy"
        name: Install mypy
      - run: "python -m mypy ."
        name: Type Checking with mypy
