name: style

on: [push, pull_request] 


jobs:
  mypy:
    name: Style Check with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install black isort"
        name: Install deps
      - run: "python -m black --check ."
        name: Style checking with black
      - run: "python -m isort --check ."
        name: Import sorting check
